//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apex.AI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid EnemyFighter = new Guid("5c2ffa03-f52a-42f7-806e-ce7096fcd7f1");

    }
}
